name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: macos
            artifact-name: IslaJournal-macOS
            artifact-path: build/macos/Build/Products/Release/isla_journal.app
            
          - os: windows-latest
            platform: windows
            artifact-name: IslaJournal-Windows
            artifact-path: build/windows/x64/runner/Release/
            
          - os: ubuntu-latest
            platform: linux
            artifact-name: IslaJournal-Linux
            artifact-path: build/linux/x64/release/bundle/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build for ${{ matrix.platform }}
        run: |
          if [ "${{ matrix.platform }}" = "linux" ]; then
            sudo apt-get update
            sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
          fi
          flutter build ${{ matrix.platform }} --release

      - name: Package macOS app
        if: matrix.platform == 'macos'
        run: |
          cd build/macos/Build/Products/Release/
          zip -r ../../../../../${{ matrix.artifact-name }}.zip isla_journal.app

      - name: Package Windows app  
        if: matrix.platform == 'windows'
        run: |
          cd build/windows/x64/runner/Release/
          7z a ../../../../../${{ matrix.artifact-name }}.zip *

      - name: Package Linux app
        if: matrix.platform == 'linux'
        run: |
          cd build/linux/x64/release/bundle/
          tar -czf ../../../../../${{ matrix.artifact-name }}.tar.gz *

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: |
            ${{ matrix.artifact-name }}.zip
            ${{ matrix.artifact-name }}.tar.gz

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            IslaJournal-macOS/IslaJournal-macOS.zip
            IslaJournal-Windows/IslaJournal-Windows.zip  
            IslaJournal-Linux/IslaJournal-Linux.tar.gz
          draft: false
          prerelease: true
          generate_release_notes: true
          body: |
            ## Isla Journal Beta Release
            
            ### 📥 Downloads
            - **macOS**: Download `IslaJournal-macOS.zip` 
            - **Windows**: Download `IslaJournal-Windows.zip`
            - **Linux**: Download `IslaJournal-Linux.tar.gz`
            
            ### 🚀 Installation
            1. Download the appropriate file for your platform
            2. Extract the archive
            3. Run the application
            
            ### ⚠️ Security Notice
            These are unsigned builds. You may need to:
            - **macOS**: Right-click → Open (bypass Gatekeeper)
            - **Windows**: Click "More info" → "Run anyway" (bypass SmartScreen)
            
            ### 🐛 Report Issues
            Found a bug? [Create an issue](https://github.com/${{ github.repository }}/issues/new)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 